imports:
  - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/clean-code.yml' }
  - { resource: '%vendor_dir%/symplify/easy-coding-standard/config/php71.yml' }

parameters:
  skip:
    SlevomatCodingStandard\Sniffs\Classes\UnusedPrivateElementsSniff.WriteOnlyProperty: ~
    SlevomatCodingStandard\Sniffs\TypeHints\TypeHintDeclarationSniff: ~
